/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
*/

class Solution {
    public char findTheDifference(String s, String t) {

    //    char[] s1 = s.toCharArray();
    //    char[] t1 = t.toCharArray();
    //     char res = ' ';
    //    Arrays.sort(s1);
    //    Arrays.sort(t1);
    //    for(int i=0;i<s1.length;i++)
    //    {
    //         if(s1[i]!=t1[i])
    //             {
    //                 return t1[i];

    //             }
    //    }
    //    return t1[t1.length-1];



    char[] schar = s.toCharArray();
    char[] tchar = t.toCharArray();
    int res = 0;
    for(int i=0;i<schar.length;i++)
    {
        res = res^schar[i];
    }
     for(int i=0;i<tchar.length;i++)
    {
        res = res^tchar[i];
    }
    return (char)res;
    }
}
